services:
  app:
    container_name: app
    build: ./backend/infra/app
    volumes:
      - .:/app
  nginx:
    container_name: nginx
    image: nginx
    working_dir: /app
    ports:
      - ${WEB_PORT}:80
    volumes:
      - .:/app
      - ./backend/infra/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./backend/infra/db/data:/var/lib/mysql
      - ./backend/infra/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/infra/db/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=${DB_NAME}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "3000:81"
    volumes:
      - ./backend/infra/phpmyadmin/sessions:/sessions

  frontend:
    container_name: frontend
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    tty: true
